name: Build and Push Docker Images

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Login
        run: echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} --password-stdin ${{ secrets.DOCKER_REGISTRY }}

      - name: Build and Push Docker Image
        run: docker buildx build --push --platform linux/amd64 -t ${{ secrets.DOCKER_REGISTRY }}/my-image:${{ github.sha }} -f Dockerfile .

      - name: Deploy to DigitalOcean
        uses: digitalocean/app_action@main
        with:
          app_name: my-app
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          image: ${{ secrets.DOCKER_REGISTRY }}/my-image:${{ github.sha }}
